"""Pydantic v2 schemas for all Stripe / payment domain objects."""
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


# ── Enums ─────────────────────────────────────────────────────────────────────

class OrderStatus(str, Enum):
    pending = "pending"
    paid = "paid"
    processing = "processing"
    shipped = "shipped"
    delivered = "delivered"
    completed = "completed"
    canceled = "canceled"
    disputed = "disputed"
    refunded = "refunded"


class PaymentStatus(str, Enum):
    pending = "pending"
    authorized = "authorized"
    held_in_escrow = "held_in_escrow"
    released = "released"
    refunded = "refunded"
    failed = "failed"
    disputed = "disputed"


class PayoutStatus(str, Enum):
    pending = "pending"
    approved = "approved"
    processing = "processing"
    paid = "paid"
    failed = "failed"


class EscrowStatus(str, Enum):
    holding = "holding"
    released = "released"
    refunded = "refunded"
    disputed = "disputed"


class ConnectAccountStatus(str, Enum):
    pending = "pending"
    onboarding = "onboarding"
    active = "active"
    restricted = "restricted"
    disabled = "disabled"


class DisputeStatus(str, Enum):
    warning_needs_response = "warning_needs_response"
    warning_under_review = "warning_under_review"
    warning_closed = "warning_closed"
    needs_response = "needs_response"
    under_review = "under_review"
    charge_refunded = "charge_refunded"
    won = "won"
    lost = "lost"


# ── Request bodies ─────────────────────────────────────────────────────────────

class CreateConnectAccountRequest(BaseModel):
    business_type: str = Field("individual", pattern="^(individual|company)$")
    country: str = Field("PK", min_length=2, max_length=2)


class RefreshOnboardingLinkRequest(BaseModel):
    mobile_id: str = Field(..., min_length=1)


class CheckoutRequest(BaseModel):
    product_id: str = Field(..., min_length=1, description="MongoDB _id of the product")
    quantity: int = Field(1, ge=1, le=1000)
    delivery_address: Optional[str] = Field(None, max_length=300)
    notes: Optional[str] = Field(None, max_length=500)
    redirect_url: Optional[str] = Field(
        None,
        max_length=500,
        description="App deep-link base URL for Stripe redirect (e.g. assankhetiapp://payment). "
                    "Generated by the mobile client via Linking.createURL(). "
                    "Falls back to FRONTEND_URL env var when absent.",
    )


class ReleasePayoutRequest(BaseModel):
    notes: Optional[str] = Field(None, max_length=500)


class RefundRequest(BaseModel):
    reason: str = Field(..., pattern="^(duplicate|fraudulent|requested_by_customer)$")
    notes: Optional[str] = Field(None, max_length=500)


class UpdateOrderStatusRequest(BaseModel):
    status: OrderStatus
    notes: Optional[str] = Field(None, max_length=500)


# ── Response shapes ────────────────────────────────────────────────────────────

class ConnectAccountOut(BaseModel):
    mobile_id: str
    stripe_account_id: str
    status: ConnectAccountStatus
    onboarding_url: Optional[str] = None
    payouts_enabled: bool
    charges_enabled: bool
    requirements: List[str] = []
    created_at: Optional[datetime] = None


class CheckoutSessionOut(BaseModel):
    checkout_url: str
    session_id: str
    order_id: str
    amount_pkr: int
    platform_fee_pkr: int
    farmer_amount_pkr: int


class OrderOut(BaseModel):
    order_id: str
    buyer_id: str
    farmer_id: str
    product_id: str
    product_name: str
    quantity: int
    unit_price_pkr: int
    subtotal_pkr: int
    platform_fee_pkr: int
    farmer_amount_pkr: int
    delivery_address: Optional[str]
    notes: Optional[str]
    status: OrderStatus
    payment_status: PaymentStatus
    stripe_session_id: Optional[str]
    stripe_payment_intent_id: Optional[str]
    created_at: datetime
    updated_at: datetime


class PayoutOut(BaseModel):
    payout_id: str
    order_id: str
    farmer_id: str
    gross_amount_pkr: int
    commission_pkr: int
    net_amount_pkr: int
    status: PayoutStatus
    stripe_transfer_id: Optional[str]
    approved_by: Optional[str]
    notes: Optional[str]
    created_at: datetime
    updated_at: datetime


class TransactionHistoryOut(BaseModel):
    order_id: str
    product_name: str
    buyer_id: str
    farmer_id: str
    amount_pkr: int
    platform_fee_pkr: int
    status: OrderStatus
    payment_status: PaymentStatus
    created_at: datetime


class WalletBalanceOut(BaseModel):
    mobile_id: str
    total_earned_pkr: int
    total_paid_out_pkr: int
    pending_payout_pkr: int
    platform_commission_pkr: int


class DisputeOut(BaseModel):
    dispute_id: str
    order_id: str
    stripe_dispute_id: str
    amount_pkr: int
    reason: str
    status: DisputeStatus
    created_at: datetime
    updated_at: datetime
