services:
  mongo:
    image: mongo:6.0
    container_name: assan-kheti-database
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - assan-kheti-net

  backend:
    build:
      context: ./app-assankheti-backend
      dockerfile: DockerfileBackend
    container_name: backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./app-assankheti-backend/src:/app/src
      - backend_data:/app/shared_data
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: "/app/src"
      MONGODB_LOCAL: "mongodb://mongo:27017"
      MONGO_DB_NAME: "${MONGO_DB_NAME:-dbasssankheti}"
    depends_on:
      - mongo
    networks:
      - assan-kheti-net

  frontend:
    build:
      context: ./app-assankheti-frontend
      dockerfile: DockerfileFrontend
      args:
        API_URL: "http://localhost:8000"
    container_name: frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-8081}:8081"
    environment:
      API_URL: "http://localhost:8000"
    depends_on:
      - backend
    networks:
      - assan-kheti-net

volumes:
  mongo_data:
    driver: local

  backend_data:
    driver: local

networks:
  assan-kheti-net:
    driver: bridge